name: carpool_connect

packages:
  - "apps/*"
  - "packages/*"

scripts:
  analyze:
    run: |
      melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
  run:mobile:
    run: |
      melos exec -c 1 --scope="mobile_app" -- "flutter run"
    description: Run the mobile app.
  test:all:
    run: |
      melos exec -c 1 -- "flutter test"
    description: Run all tests in the workspace.
  build:apk:
    run: |
      melos exec -c 1 --scope="mobile_app" -- "flutter build apk"
    description: Build the Android APK.
  build_runner:
    run: |
      melos exec -c 1 --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner for all packages.
